Feature/enhance data migration
ONSdigital/dp-data-tools pull request #35
Opened 2021-11-24 17:06 UTC by Marianasilvago

Changes:

Add validation to zebedee users migration script and upload files to S3

How to check?

Verify the code changes

Who can check?
Anyone.

2021-12-01 17:26 UTC, AWitcherONS submitted a review, later dismissed
Just one spelling mistake given that you have found more of mine

2021-12-01 18:22 UTC, rafahop commented on dp-identity-data-migration/userdataextraction/user_extraction.go
> +		if isValidEmail := validateEmailId(validEmailDomains, user.Email); isValidEmail {
Do we need a variable?

```suggestion
		if validateEmailId(validEmailDomains, user.Email) {
```

2021-12-01 18:22 UTC, rafahop commented on dp-identity-data-migration/userdataextraction/user_extraction.go
> +			if err := invalidUsersWriter.Write(convert_to_slice(csvline)); err != nil {
`convert_to_slice(csvline)` is run no matter what (in both sides of the if) so maybe consider moving it up to line 173 and use a variable?

2021-12-01 18:22 UTC, rafahop commented on dp-identity-data-migration/userdataextraction/user_extraction.go
> +	domainName := strings.Split(emailID, "@")[1]
What if the `emailID` did not contain the `@` symbol?

2021-12-01 18:22 UTC, rafahop commented on dp-identity-data-migration/userdataextraction/user_extraction.go
> +		if strings.Contains(domain, domainName) {
I wonder whether we should use exact matches?

2021-12-01 18:22 UTC, rafahop requested changes
Please run `go fmt` for both go files

2021-12-02 16:14 UTC, rafahop approved these changes
Looks good to me

2021-12-02 16:17 UTC, merged