Fix kafka drain instructions
ONSdigital/dp-data-tools pull request #39
Opened 2022-03-15 14:57 UTC by cookel2

# What has changed

Documentation has been updated to further clarify how to drain a kafka topic.

These changes also fix the problem of the dollar sign being copied when the commands are copied from the git UI.

# How to review

Check that the documentation looks correct.

# Who can review

Anyone but me

2022-03-15 17:00 UTC, nshumoogum requested changes

2022-03-15 17:20 UTC, cookel2 commented on kafka-tools/drain-topic/README.md
> +This will remove remote files (in the env) and local build files:
I've made that change, thanks.

2022-04-26 12:46 UTC, nshumoogum approved these changes

2022-04-26 12:46 UTC, nshumoogum commented on kafka-tools/drain-topic/README.md
> +git switch main   && git pull             #   get up-to-date
Suggest removing extra whitespace
```suggestion
git switch main && git pull             # get up-to-date
```

2022-04-26 12:59 UTC, nshumoogum approved these changes

2022-04-26 13:01 UTC, merged